### PR TITLE
Optimize Marshaller.GStrdup calls

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by DavidKarlas** [comment]
LGTM

**Comment by Therzok** [comment]
build

**Comment by bratsche** [comment]
Nice!

**Comment by Therzok** [comment]
Yeah, this enforces .NET 4.6 dependency on Windows, so I'm not sure how to ship the GetString(byte *) part.

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
Closing for now, as there is an optimized way to do this without depending on .NET 4.6 in 2-12. I'll backport when I have spare cycles.

**Pull request closed without merging**
