### PR TITLE
Update csproj ToolsVersion to 4.0

### PR DESCRIPTION
**Pull request by riccioclista**
This PR changes the ToolsVersion in the csproj files from 3.5 to 4.0 because 3.5 is not available any more on newer mono versions.

### CODE REVIEW

**Comment by antoniusriha** [comment]
@Therzok, I think this is something that can be merged safely too.

**Comment by Therzok** [comment]
This could break users still targeting .NET 3.5 on platforms which still provide it.

**Comment by directhex** [comment]
build

**Comment by knocte** [comment]
@antoniusriha sorry to come so late to review this.

The commit message should be expanded to contain the explanation that you have in the PR.

Also, it's not entirely clear what "because 3.5 is not available any more on newer mono versions" means. What's the consequence of not being available? A build failure? The projects don't load in MonoDevelop? A MSBuild-only build failure? Would be great to explain this also in the commit message, and then I guess we can merge this.

**Pull request closed without merging**
