### PR TITLE
[Gen] Don't generate extra array allocations for signals.

### PR DESCRIPTION
**Pull request by Therzok**
https://gist.github.com/Therzok/da422b1d097350eda25ea463545d2c23

cc @DavidKarlas @alanmcgovern

### CODE REVIEW

**Comment by meebey** [comment]
That will lead to leaks if the managed code throws an exception before the Dispose() call

**Comment by Therzok** [comment]
I am so sorry, the diff should be viewed in reverse.

**Comment by Therzok** [comment]
Sorry, updated the gist now. It was a reversed diff.

**Comment by meebey** [comment]
LGTM now :)

**Pull request merged**
