### PR TITLE
Implement IEquatable on structs

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
cc @alanmcgovern

**Comment by alanmcgovern** [comment]
Btw, this means if we compile with this Gtk# we won't be able to run under an older one. We should bump XS's minimum requirement once we start using this

**Comment by Therzok** [comment]
Actually, you're right. This isn't a backwards compatible change.

**Comment by Therzok** [comment]
Will keep these for post-C9 too.

**Comment by alanmcgovern** [comment]
👍

**Pull request merged**
