### PR TITLE
Review gapi annotations

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
👀 @alanmcgovern @DavidKarlas

**Comment by Therzok** [comment]
Merging as I want a new build with this toy.

**Comment by knocte** [comment]
how did the toy go?

**Comment by Therzok** [comment]
With a few fixes applied, TreeView was finally correctly generated. Given current tip of master (source fix) Gtk# is not leaking anymore for XS. Whatever is leaking in XS is a pure XS leak. :100:

**Pull request merged**
