### PR TITLE
[Gtk,Pango] Unbreak the API.

### PR DESCRIPTION
**Pull request by Therzok**
https://gist.github.com/Therzok/7cbf3d2042d9e6c2aabe23fdcc957415

This contains all the fixes, except struct API break.

### CODE REVIEW

**Comment by knocte** [comment]
Can you specify in the commit message the commit hashes that broke the API?

**Comment by Therzok** [comment]
Done.

**Comment by alanmcgovern** [comment]
Where do we normally keep track of release notes so we can point out that future releases will still not API/ABI compatible with previous releases due to the struct change?

**Comment by Therzok** [comment]
Mono and/or Gtk# release tags

**Pull request merged**
