### PR TITLE
[Gen] Generate owned variant for opaques if possible.

### PR DESCRIPTION
**Pull request by Therzok**
https://gist.github.com/Therzok/371ac6b35df880b590a39ec968cb57bc

### CODE REVIEW

**Comment by Therzok** [comment]
cc @alanmcgovern @DavidKarlas

**Comment by knocte** [comment]
What's the **why** here? What happens if this patch is not applied? Double free? Leak?

**Comment by Therzok** [comment]
@knocte amended commit with explanation

**Comment by alanmcgovern** [comment]
:+1:

**Comment by knocte** [comment]
Thanks.

(BTW the last two commits should have been "Gtk: " and "Pango: ", not [Misc])

**Comment by Therzok** [comment]
Yeah, you're right. I'll fix that on forward-port to master.

**Pull request merged**
