### PR TITLE
[List] Don't cache the Count value.

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by knocte** [comment]
You stated the *what*, but not the *why*.

**Comment by meebey** [comment]
Seems like to save 32bit as class member. More interesting is that it was only invalidated in FreeList, as the list size was static?

**Comment by Therzok** [comment]
Yes, you are right, I did not state the why.

The problem is that if by per-chance you iterate the list created from managed and append more elements, the list size is wrong and you won't iterate everything.

**Comment by Therzok** [comment]
This is for API correctness, SList/List should _not_ be iterated via indexer and Count.

**Comment by knocte** [comment]
Ok thanks. Given that this is a clear bugfix I guess we can include this one in the next 3.0 release, so you can forward port now if you want (and include the **why** in the forward port commit).

**Pull request merged**
