### PR TITLE
Update atk to version 2.14.0

### PR DESCRIPTION
**Pull request by nacho**
This is more of a check to see if the project is alive at the point of discussing changes.
 - For some reason I had to revert that patch since after cloning I get some crlf changes that I cannot remove unless I make a commit.
 - Then basically there are a few patches to update atk to the version 2.14.0 which is the version in centos 7.2

My idea would be to update all the packages so we target gtk 3.14. Then release and make a branch out of it.
Then it would be a matter of updating the project to the last gtk stable which currently is 3.20 and release again and branch.
And finally target gtk master.

Ideas on this? A review on the patches would be great as well, and getting them merged even better.

### CODE REVIEW

**Comment by Therzok** [comment]
https://github.com/mono/gtk-sharp/pull/139/commits/8dbbfea88d7af7cf6fe8289399a8baeaf5112a9e 👍 

The rest of them look good to me too.

**Comment by nacho** [comment]
There we go, I just removed the revert from the pull request

**Comment by knocte** [comment]
Any particular reason why both GDK and ATK update are in the same pull request?

Also, you should add the **why** of your commits https://github.com/mono/gtk-sharp/pull/139/commits/6d774dc26a1f38aee9d8611ca6c541bebf91651a and https://github.com/mono/gtk-sharp/pull/139/commits/c0d7839df24c90bfad73756b87bf84055950a271 , not only the **what**.

**Comment by nacho** [comment]
@knocte right, I'll create a different pull request for the gdk one and I'll change the patches to include the why. Thanks for the review.

**Comment by nacho** [comment]
It should be updated now. Please let me know if I should change something else. Thanks

**Comment by nacho** [comment]
ping

**Comment by Therzok** [comment]
build

**Pull request merged**
