### PR TITLE
Ui thread check

### PR DESCRIPTION
**Pull request by Therzok**
https://gist.github.com/Therzok/dd98f69572b8e1a4f204e63aead194e0

### CODE REVIEW

**Comment by Therzok** [comment]
The generator for properties only generates the MainThread check on setters, not getters, will add for getters _if needed_.

**Comment by Therzok** [comment]
I'm still not sure whether this should throw an exception or log a stacktrace, because this can cause guaranteed app breaks vs a random crasher in some specific concurrency case.

**Comment by slluis** [comment]
We can start with a log.

**Comment by Therzok** [comment]
Switched to logging. Merging as soon as build is green.

**Pull request merged**
